### ISSUE TITLE
handshake_ephemeral must be 'none'

### ISSUE THREAD

**Issue by bushsf** [ssp21/ssp21-cpp#14]
I have SSP21 running on two clean NUCs and am using the github repository to build the code with:
git commit date: 2019-08-06
git commit hash: 21591b1367e261f1c081e3009821b71dd040cc03

The responder is ready and waiting, but the initiator returns the following message. The configuration files are included below. QIX keys are being sent successfully.
What is the problem?
tsn@tsn-nuc4:~/ssp21/qkd/remote_test$ proxy ./initiator_udp.ini 
ms(1565471806992) ssp21-proxy-qix      info    Reading QIX frames on: /home/tsn/ssp21/qkd/device/remoteOut
ms(1565471806993) ssp21-proxy          event   initializing UDP proxy: i-proxyA
ms(1565471806993) i-proxyA             info    receiving raw traffic on 127.0.0.1:20000, wrapping in SSP21, and sending to 192.168.1.127:20003
ms(1565471806993) i-proxyA             info    receiving SSP21 traffic on 0.0.0.0:20002, unwrapping, and sending raw traffic to 127.0.0.1:20001
handshake_ephemeral must be 'none'
[r-proxy]
proto_type=udp
crypto_only=true
mode=responder
handshake_mode=qkd
serial_port=/home/tsn/ssp21/qkd/device/remoteOut
log_levels=iwemf
raw.rx.ip = 127.0.0.1
raw.rx.port = 20004
raw.tx.ip = 127.0.0.1
raw.tx.port = 20005
secure.rx.ip = 0.0.0.0
secure.rx.port = 20003
secure.tx.ip = 192.168.1.126
secure.tx.port = 20002

[r-proxy]
proto_type=udp
crypto_only=true
mode=responder
handshake_mode=qkd
serial_port=/home/tsn/ssp21/qkd/device/localOut
log_levels=iwemf
raw.rx.ip = 127.0.0.1
raw.rx.port = 20004
raw.tx.ip = 127.0.0.1
raw.tx.port = 20005
secure.rx.ip = 0.0.0.0
secure.rx.port = 20003
secure.tx.ip = 192.168.1.126
secure.tx.port = 20002

**Comment by jadamcrain** [comment]
Thanks, I'll stand this up first thing Monday morning.

**Comment by jadamcrain** [comment]
I'm at a loss here. I can't replicate this error with this version. Is it possible that you have an old version of the SSP21 library lurking around somewhere? Can you run LDD on your `proxy` application and see which SSP21 library it is loading?

**Comment by bushsf** [comment]
There is no way it could be an old version since I’ve used brand new (clean) computers and am using the latest from the repository.
Yes, I can run LDD when I get back to the lab tomorrow.
The git version hash that you added seems correct, right?

Stephen F Bush

**Comment by bushsf** [comment]
ldd -v information follows:

tsn@tsn-nuc4:~/ssp21$ ldd -v /usr/local/bin/proxy
    linux-vdso.so.1 =>  (0x00007fffe88db000)
    libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fa276a30000)
    libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fa2766ae000)
    libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fa276498000)
    libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fa2760ce000)
    /lib64/ld-linux-x86-64.so.2 (0x00007fa276c4d000)
    libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fa275dc5000)

    Version information:
    /usr/local/bin/proxy:
        libgcc_s.so.1 (GCC_3.0) => /lib/x86_64-linux-gnu/libgcc_s.so.1
        libc.so.6 (GLIBC_2.3.4) => /lib/x86_64-linux-gnu/libc.so.6
        libc.so.6 (GLIBC_2.9) => /lib/x86_64-linux-gnu/libc.so.6
        libc.so.6 (GLIBC_2.7) => /lib/x86_64-linux-gnu/libc.so.6
        libc.so.6 (GLIBC_2.4) => /lib/x86_64-linux-gnu/libc.so.6
        libc.so.6 (GLIBC_2.3) => /lib/x86_64-linux-gnu/libc.so.6
        libc.so.6 (GLIBC_2.14) => /lib/x86_64-linux-gnu/libc.so.6
        libc.so.6 (GLIBC_2.8) => /lib/x86_64-linux-gnu/libc.so.6
        libc.so.6 (GLIBC_2.3.2) => /lib/x86_64-linux-gnu/libc.so.6
        libc.so.6 (GLIBC_2.2.5) => /lib/x86_64-linux-gnu/libc.so.6
        libstdc++.so.6 (GLIBCXX_3.4.15) => /usr/lib/x86_64-linux-gnu/libstdc++.so.6
        libstdc++.so.6 (CXXABI_1.3.9) => /usr/lib/x86_64-linux-gnu/libstdc++.so.6
        libstdc++.so.6 (CXXABI_1.3) => /usr/lib/x86_64-linux-gnu/libstdc++.so.6
        libstdc++.so.6 (GLIBCXX_3.4.14) => /usr/lib/x86_64-linux-gnu/libstdc++.so.6
        libstdc++.so.6 (GLIBCXX_3.4.11) => /usr/lib/x86_64-linux-gnu/libstdc++.so.6
        libstdc++.so.6 (GLIBCXX_3.4.19) => /usr/lib/x86_64-linux-gnu/libstdc++.so.6
        libstdc++.so.6 (GLIBCXX_3.4.21) => /usr/lib/x86_64-linux-gnu/libstdc++.so.6
        libstdc++.so.6 (GLIBCXX_3.4) => /usr/lib/x86_64-linux-gnu/libstdc++.so.6
        libpthread.so.0 (GLIBC_2.3.3) => /lib/x86_64-linux-gnu/libpthread.so.0
        libpthread.so.0 (GLIBC_2.2.5) => /lib/x86_64-linux-gnu/libpthread.so.0
        libpthread.so.0 (GLIBC_2.3.2) => /lib/x86_64-linux-gnu/libpthread.so.0
    /lib/x86_64-linux-gnu/libpthread.so.0:
        ld-linux-x86-64.so.2 (GLIBC_2.2.5) => /lib64/ld-linux-x86-64.so.2
        ld-linux-x86-64.so.2 (GLIBC_PRIVATE) => /lib64/ld-linux-x86-64.so.2
        libc.so.6 (GLIBC_2.14) => /lib/x86_64-linux-gnu/libc.so.6
        libc.so.6 (GLIBC_2.3.2) => /lib/x86_64-linux-gnu/libc.so.6
        libc.so.6 (GLIBC_2.2.5) => /lib/x86_64-linux-gnu/libc.so.6
        libc.so.6 (GLIBC_PRIVATE) => /lib/x86_64-linux-gnu/libc.so.6
    /usr/lib/x86_64-linux-gnu/libstdc++.so.6:
        ld-linux-x86-64.so.2 (GLIBC_2.3) => /lib64/ld-linux-x86-64.so.2
        libm.so.6 (GLIBC_2.2.5) => /lib/x86_64-linux-gnu/libm.so.6
        libgcc_s.so.1 (GCC_4.2.0) => /lib/x86_64-linux-gnu/libgcc_s.so.1
        libgcc_s.so.1 (GCC_3.3) => /lib/x86_64-linux-gnu/libgcc_s.so.1
        libgcc_s.so.1 (GCC_3.0) => /lib/x86_64-linux-gnu/libgcc_s.so.1
        libc.so.6 (GLIBC_2.14) => /lib/x86_64-linux-gnu/libc.so.6
        libc.so.6 (GLIBC_2.4) => /lib/x86_64-linux-gnu/libc.so.6
        libc.so.6 (GLIBC_2.18) => /lib/x86_64-linux-gnu/libc.so.6
        libc.so.6 (GLIBC_2.3.4) => /lib/x86_64-linux-gnu/libc.so.6
        libc.so.6 (GLIBC_2.3) => /lib/x86_64-linux-gnu/libc.so.6
        libc.so.6 (GLIBC_2.17) => /lib/x86_64-linux-gnu/libc.so.6
        libc.so.6 (GLIBC_2.3.2) => /lib/x86_64-linux-gnu/libc.so.6
        libc.so.6 (GLIBC_2.2.5) => /lib/x86_64-linux-gnu/libc.so.6
    /lib/x86_64-linux-gnu/libgcc_s.so.1:
        libc.so.6 (GLIBC_2.14) => /lib/x86_64-linux-gnu/libc.so.6
        libc.so.6 (GLIBC_2.2.5) => /lib/x86_64-linux-gnu/libc.so.6
    /lib/x86_64-linux-gnu/libc.so.6:
        ld-linux-x86-64.so.2 (GLIBC_2.3) => /lib64/ld-linux-x86-64.so.2
        ld-linux-x86-64.so.2 (GLIBC_PRIVATE) => /lib64/ld-linux-x86-64.so.2
    /lib/x86_64-linux-gnu/libm.so.6:
        ld-linux-x86-64.so.2 (GLIBC_PRIVATE) => /lib64/ld-linux-x86-64.so.2
        libc.so.6 (GLIBC_2.2.5) => /lib/x86_64-linux-gnu/libc.so.6
        libc.so.6 (GLIBC_PRIVATE) => /lib/x86_64-linux-gnu/libc.so.6
tsn@tsn-nuc4:~/ssp21$

Stephen F Bush

From: Bush, Stephen F (GE Global Research, US)
Sent: Tuesday, August 13, 2019 1:36 PM
To: ssp21/ssp21-cpp <reply@reply.github.com>; ssp21/ssp21-cpp <ssp21-cpp@noreply.github.com>
Cc: Author <author@noreply.github.com>
Subject: RE: Re: [ssp21/ssp21-cpp] handshake_ephemeral must be 'none' (#14)

There is no way it could be an old version since I’ve used brand new (clean) computers and am using the latest from the repository.
Yes, I can run LDD when I get back to the lab tomorrow.
The git version hash that you added seems correct, right?

Stephen F Bush

**Comment by jadamcrain** [comment]
There was a difference between how TCP vs UDP was initialized:

https://github.com/ssp21/ssp21-cpp/commit/87de125c38311185130e3910aa9e485b80e838b

Try the latest

**Comment by bushsf** [comment]
After updating and recompiling, I no longer receive the “handshake_ephemeral must be 'none' error.”

However, I’m having problems using nc to test it. My understanding of the new proxy labeling is that the “raw” {ip,port} fields would connect to local applications at either end-system.
I use “echo “test” | nc -u 127.0.0.1 <corresponding raw rx/tx port from config file>.” It returns the error “address already in use.” How do I connect via nc to the proxy?

Stephen F Bush
