### ISSUE TITLE
Inconsistent use of auth_len and user_len

### ISSUE THREAD

**Issue by gmantelet** [ssp21/ssp21-cpp#19]
Auth_len and user_len are expected of type uint16_t to allow for up to roughly 4096 bytes of payload. 
We can observe instead the following behavior from a qkd initiator proxy:

1. auth_request: Immediately following valid_until_ms field 0010 which is being interpreted as "no user data" and 16 bytes of authentication tag as expected. The following tag matches the signature obtained through handshake using hkdf.
2. session_data carrying a small message (e.g. HELLO!) shows that user_length is in fact of type uint8_t: 030001000027160648454C4C4F2110FB111E52D512861C4664ACE21C231CAC shows that it is a session_data packet with nonce 1 and a validity of 0x2716 ms. Then we have a payload of 0x06 bytes of data (48454C4C4F21 = HELLO!) and then user_length equals 0x10 immediately followed by the expected signature. We expect instead user_length to be 0x0006 and not 0x06, and auth_len to be either 0x10 (if auth tag are always less than 256 of length) or 0x0010 for consistency.
3. When the payload exceeds 256 bytes of length, user_length seems to be a uint16_t field: 0300010000271E9802**3C3F786D6C2076657273696F6E3D22312E302220656E636F64696E673D225554462D38223F3E0D0A0A3C6E633A68656C6C6F20786D6C6E733A6E633D2275726E3A696574663A706172616D733A786D6C3A6E733A6E6574636F6E663A626173653A312E30223E0D0A0A20203C6E633A6361706162696C69746965733E0D0A0A202020203C6E633A6361706162696C6974793E75726E3A696574663A706172616D733A6E6574636F6E663A626173653A312E303C2F6E633A6361706162696C6974793E0D0A0A202020203C6E633A73657373696F6E2D69643E7B7D3C2F6E633A73657373696F6E2D69643E0D0A0A20203C2F6E633A6361706162696C69746965733E0D0A0A3C2F6E633A68656C6C6F3E0D0A0A5D5D3E5D5D3E**10021FC64EB5E1177FB3F1762C410B322F. Here we higlighted the payload (0x3C in ASCII corresponding to '<' which is the beginning of our XML document). However 0x9802 or 0x0298 does not seem to be the right length (we expect 280 => 0x118).

We expect that user_length should be uint16-t, being eventually not present if no payload is encapsulated within the message as this is the case with auth_request messages, being equal to 0x0006 with small payloads and to properly reflect the right payload length when payload is greater than 256 octets. 

Seen with ./proxy -v
2019-11-18
**53fd56c**84bc7bbeff39ed75ea32878686414d8b9

**Comment by jadamcrain** [comment]
https://ssp21.github.io/spec/latest/html/index.html#variable-length-count

Although we might consider changing it to something more ASN DER like... as shifting 7 bits at a time is kind of odd.
