### ISSUE TITLE
Generated structures do not follow the spec

### ISSUE THREAD

**Issue by emgre** [ssp21/ssp21-cpp#3]
I don't know if the issue is on the spec or the ref implementation, but the structures generated by the codegen does not follow the same order as the spec.

- CryptoSpec should be `[HandshakeEphemeral, HandshakeHash, HandshakeKDF, NonceMode, SessionMode]` according to the spec.
- RequestHandshakeBegin should be `[Version, HandshakeMode, CryptoSpec, SessionConstraints, EphemeralData, HandshakeData]` according to the spec.
- `HandshakeMode` should be named `TrustMode`, and `HandshakeData` should be named `ModeData`.

See https://github.com/aegis4ics/ssp21-cpp/blob/master/codegen/ssp21/src/main/scala/com/automatak/render/ssp21/messages/RequestHandshakeBegin.scala

**Comment by jadamcrain** [comment]
Names of all enums, structures have been normalized between the reference implementation and the spec.
